In [3]:
from glio.loaders import niiread, niiwrite_nib, niiread_affine
import nibabel as nib
path = r"E:\dataset\BRaTS2024-GoAT\ISBI2024-BraTS-GoAT-TrainingData\BraTS-GoAT-00006\BraTS-GoAT-00006-t1c.nii.gz"
nii = nib.load(path)
print(nii.affine)

[[ -1.   0.   0.  -0.]
 [  0.  -1.   0. 239.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]


In [8]:
img = niiread(path)
aff = niiread_affine(path)
niiwrite_nib(r"F:\Stuff\Programming\experiments\vkr\test.nii.gz", img, aff)

In [10]:
from glio.jupyter_tools import show_slices, show_slices_arr
show_slices_arr(img)

interactive(children=(Checkbox(value=False, description='color'), Text(value='0 1 2', description='permute'), …

<function glio.jupyter_tools.show_slices_arr.<locals>.f(color, permute: str, **kwargs)>

In [12]:
from glio.loaders import niireadtensor
from glio.python_tools import find_file_containing
import torch
dcmpath = r'E:\dataset\BRaTS2024-GoAT\ISBI2024-BraTS-GoAT-TrainingData\BraTS-GoAT-00000'
t1c = niireadtensor(find_file_containing(dcmpath, "t1c")) # type:ignore
t1n = niireadtensor(find_file_containing(dcmpath, "t1n")) # type:ignore
t2f = niireadtensor(find_file_containing(dcmpath, "t2f")) # type:ignore
t2w = niireadtensor(find_file_containing(dcmpath, "t2w")) # type:ignore
affine = niiread_affine(find_file_containing(dcmpath, "t1c")) # type:ignore
images = torch.stack((t1c,t1n,t2f,t2w)).permute(3,0,2,1)
show_slices_arr(images)

interactive(children=(Checkbox(value=False, description='color'), Text(value='0 1 2 3', description='permute')…

<function glio.jupyter_tools.show_slices_arr.<locals>.f(color, permute: str, **kwargs)>